version: '3.7'

services:

  frontend:
    container_name: beer_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6969:3000
    depends_on:
      - backend
    links:
      - backend
  
  backend:
    container_name: beer_backend
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - 8080:8080