version: '3.3'

services:

  frontend:
    container_name: beer_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3440:3000
      
  backend:
    container_name: beer_backend
    build:
      context: .
      dockerfile: Dockerfile.python