version: '3'

services:

  frontend:
    container_name: beer_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3440:3000
    environment:
      - REACT_APP_API_BASE_URL=host.docker.internal
    networks:
      - beer
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      
  backend:
    container_name: beer_backend
    build:
      context: .
      dockerfile: Dockerfile.python
    networks:
      - beer
    ports:
      - 80:8080

networks:
  beer:
    driver: bridge