version: '1.17.1'

services:

  frontend:
    container_name: beer_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6969:3000
  
  backend:
    container_name: beer_backend
    build:
      context: .
      dockerfile: Dockerfile.python