FROM python:3

WORKDIR /app

COPY ./pythonFiles/*.py ./pythonFiles/
COPY ./pythonFiles/beer-dataset ./pythonFiles/beer-dataset

RUN pip install flask
RUN pip install waitress
RUN pip install pandas

RUN python ./pythonFiles/filtering.py
RUN python ./pythonFiles/generateDict.py

CMD [ "python", "./pythonFiles/api.py" ]