version: '3'

services:

  frontend:
    container_name: beer_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3441:3000
    environment:
      - REACT_APP_API=http://localhost:3440/api
    networks:
      - beer
      
  backend:
    container_name: beer_backend
    build:
      context: .
      dockerfile: Dockerfile.python
    networks:
      - beer
    ports:
      - 3442:8080

  engine:
    container_name: beer_proxy
    build:
      context: .
      dockerfile: Dockerfile.proxy
    networks:
      - beer
    ports:
      - 3440:80
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - backend
      - frontend

networks:
  beer:
    driver: bridge